.pragma library

// code -> endonym (display name). Generated from `trans -T`.
// Languages use CODES internally (trans -speak needs codes); this maps
// a code to a human-friendly name for display only.
const NAMES = {
    "af": "Afrikaans",
    "am": "አማርኛ",
    "ar": "العربية",
    "as": "অসমীয়া",
    "ay": "Aymar aru",
    "az": "Azərbaycanca",
    "ba": "Башҡортса",
    "be": "беларуская",
    "bg": "български",
    "bho": "भोजपुरी",
    "bm": "Bamanankan",
    "bn": "বাংলা",
    "bo": "བོད་ཡིག",
    "bs": "Bosanski",
    "ca": "Català",
    "ceb": "Cebuano",
    "ckb": "سۆرانی",
    "co": "Corsu",
    "cs": "Čeština",
    "cv": "Чӑвашла",
    "cy": "Cymraeg",
    "da": "Dansk",
    "de": "Deutsch",
    "doi": "डोगरी",
    "dv": "ދިވެހި",
    "ee": "Eʋegbe",
    "el": "Ελληνικά",
    "en": "English",
    "eo": "Esperanto",
    "es": "Español",
    "et": "Eesti",
    "eu": "Euskara",
    "fa": "فارسی",
    "fi": "Suomi",
    "fj": "Vosa Vakaviti",
    "fo": "Føroyskt",
    "fr": "Français",
    "fy": "Frysk",
    "ga": "Gaeilge",
    "gd": "Gàidhlig",
    "gl": "Galego",
    "gn": "Avañe'ẽ",
    "gom": "कोंकणी",
    "gu": "ગુજરાતી",
    "ha": "Hausa",
    "haw": "ʻŌlelo Hawaiʻi",
    "he": "עִבְרִית",
    "hi": "हिन्दी",
    "hmn": "Hmoob",
    "hr": "Hrvatski",
    "hsb": "Hornjoserbšćina",
    "ht": "Kreyòl Ayisyen",
    "hu": "Magyar",
    "hy": "Հայերեն",
    "id": "Bahasa Indonesia",
    "ig": "Igbo",
    "ikt": "Inuinnaqtun",
    "ilo": "Ilokano",
    "is": "Íslenska",
    "it": "Italiano",
    "iu": "ᐃᓄᒃᑎᑐᑦ",
    "ja": "日本語",
    "jv": "Basa Jawa",
    "ka": "ქართული",
    "kk": "Қазақ тілі",
    "km": "ភាសាខ្មែរ",
    "kn": "ಕನ್ನಡ",
    "ko": "한국어",
    "kri": "Krio",
    "ku": "Kurmancî",
    "ky": "Кыргызча",
    "la": "Latina",
    "lb": "Lëtzebuergesch",
    "lg": "Luganda",
    "ln": "Lingála",
    "lo": "ລາວ",
    "lt": "Lietuvių",
    "lus": "Mizo ṭawng",
    "lv": "Latviešu",
    "lzh": "文言",
    "mai": "मैथिली",
    "mg": "Malagasy",
    "mhr": "Олык марий",
    "mi": "Māori",
    "mk": "Македонски",
    "ml": "മലയാളം",
    "mn": "Монгол",
    "mr": "मराठी",
    "mrj": "Кырык мары",
    "ms": "Bahasa Melayu",
    "mt": "Malti",
    "my": "မြန်မာစာ",
    "ne": "नेपाली",
    "nl": "Nederlands",
    "no": "Norsk",
    "nso": "Sepedi",
    "ny": "Nyanja",
    "om": "Afaan Oromoo",
    "or": "ଓଡ଼ିଆ",
    "otq": "Hñąñho",
    "pa": "ਪੰਜਾਬੀ",
    "pap": "Papiamentu",
    "pl": "Polski",
    "prs": "دری",
    "ps": "پښتو",
    "qu": "Runasimi",
    "ro": "Română",
    "ru": "Русский",
    "rw": "Ikinyarwanda",
    "sa": "Inuktitut        -iu-Latn संस्कृतम्",
    "sah": "Sakha",
    "sd": "سنڌي",
    "si": "සිංහල",
    "sk": "Slovenčina",
    "sl": "Slovenščina",
    "sm": "Gagana Sāmoa",
    "sn": "chiShona",
    "so": "Soomaali",
    "sq": "Shqip",
    "st": "Sesotho",
    "su": "Basa Sunda",
    "sv": "Svenska",
    "sw": "Kiswahili",
    "ta": "தமிழ்",
    "te": "తెలుగు",
    "tg": "Тоҷикӣ",
    "th": "ไทย",
    "ti": "ትግርኛ",
    "tk": "Türkmen",
    "tl": "Filipino",
    "to": "Lea faka-Tonga",
    "tr": "Türkçe",
    "ts": "Xitsonga",
    "tt": "ᠮᠣᠩᠭᠣᠯ           -mn-Mong татарча",
    "tw": "ꯃꯤꯇꯩꯂꯣꯟ          mni-Mtei Twi",
    "ty": "Reo Tahiti",
    "udm": "Удмурт",
    "ug": "ئۇيغۇر تىلى",
    "uk": "Українська",
    "ur": "اُردُو",
    "uz": "Oʻzbek tili",
    "vi": "Tiếng Việt",
    "xh": "isiXhosa",
    "yi": "ייִדיש",
    "yo": "Yorùbá",
    "yua": "Màaya T'àan",
    "yue": "粵語",
    "zh-CN": "简体中文",
    "zh-TW": "繁體中文",
    "zu": "isiZulu",
};

function display(code) {
    if (code === "auto") return "auto";
    return NAMES[code] || code;
}
